# Type stub for linting and IDEs. Do not import at runtime.
# Pylint: skip checking to avoid false positives on stubs
# pylint: skip-file
from typing import List, Optional


class Tensor:
    def __init__(self, value: List[float], shape: List[int], dtype: Optional[str] = None): ...

    def softmax_cross_entropy_with_logits(self, targets: 'Tensor'): ...

    def backward(self) -> None: ...

    def get_data(self) -> List[float]: ...

    def get_grad(self) -> Optional[List[float]]: ...

    def log_softmax(self, axis: int) -> 'Tensor': ...

    def quantize_weights(self, dtype: str, block_size: Optional[int]) -> 'Tensor': ...

    def quantized_matmul(self, qweight: 'Tensor') -> 'Tensor': ...

    @property
    def dtype(self) -> str: ...

    @property
    def shape(self) -> List[int]: ...


class Labels:
    def __init__(self, indices: List[int]): ...

    def to_one_hot(self, num_classes: int) -> Tensor: ...


class NLLLoss:
    def forward(self, logits: Tensor, labels: Tensor) -> Tensor: ...

    def forward_from_labels(self, logits: Tensor, labels: Labels) -> Tensor: ...


class SoftmaxCrossEntropyLoss:
    def forward(self, logits: Tensor, targets: Tensor) -> Tensor: ...

    def forward_from_labels(self, logits: Tensor, labels: Labels) -> Tensor: ...


class CrossEntropyLogitsLoss:
    def forward(self, logits: Tensor, labels: Tensor) -> Tensor: ...
